### ISSUE TITLE
for the functions about WaveGen

### ISSUE THREAD

**Issue by Wang-Yining-Nicola** [danchitnis/pyscpi#1]
**Describe the bug**
osc.setWGenPulse(osci, 0, 10, 0, 0.000000060, 0.000000020)

For the setWGenPulse function, changing the period and pulsewidth are not useful. On the oscilloscope they show the same waveform. Or the setting about timing is wrong.

**Screenshots**
![1677594180854](https://user-images.githubusercontent.com/71167049/221882157-f534a9aa-9f8c-4a95-b260-672bf48d55b3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - pyscpi version:  0.5.0
 - Connection method: Socket

**Comment by danchitnis** [comment]
@Wang-Yining-Nicola is this only for `WGenPulse` or others as well like sine wave etc?

**Comment by Wang-Yining-Nicola** [comment]
It's only for wavegenpulse. Sinewave and square wave work fine as their periods are defined by frequency. I don't know whether this is the reason. Or the number is too small to be recognized by Python.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Danial ***@***.***> |
| Date | 02/28/2023 20:51 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [danchitnis/pyscpi] for the functions about WaveGen (Issue #1) |

@Wang-Yining-Nicola is this only for WGenPulse or others as well like sine wave etc?

**Comment by Wang-Yining-Nicola** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/71167049/222925011-4b40c36f-6912-4e55-bb35-823684c7c135.png">
From keysight command expert, the period can also be set by frequency. But the frequency range is from 10mHz to 10MHz, which means the period should be set between the range 100ns to 10s.
<img width="328" alt="image" src="https://user-images.githubusercontent.com/71167049/222925071-1437d25c-4e9b-4ad9-b567-f40694a62b4c.png">
The notes for this function says the period should be in the range from 10ns to 100ns. I think maybe that is the problem why after I change the period between 10ns to 100ns, the waveform does not change. It is supposed to be set a larger number.
Maybe the notes can be changed latter and I will try next week whether changing the period range between 100ns and 10s would change the waveform.

**Comment by Wang-Yining-Nicola** [comment]
> <img alt="image" width="317" src="https://user-images.githubusercontent.com/71167049/222925011-4b40c36f-6912-4e55-bb35-823684c7c135.png">
> 
> From keysight command expert, the period can also be set by frequency. But the frequency range is from 10mHz to 10MHz, which means the period should be set between the range 100ns to 10s.
> <img alt="image" width="328" src="https://user-images.githubusercontent.com/71167049/222925071-1437d25c-4e9b-4ad9-b567-f40694a62b4c.png">
> 
> The notes for this function says the period should be in the range from 10ns to 100ns. I think maybe that is the problem why after I change the period between 10ns to 100ns, the waveform does not change. It is supposed to be set a larger number. Maybe the notes can be changed latter and I will try next week whether changing the period range between 100ns and 10s would change the waveform.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/71167049/222925324-c1ac8905-7c44-41e5-8ddc-e22c7e8ae24f.png">

**Comment by Wang-Yining-Nicola** [comment]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/71167049/222925691-e410d769-f84d-4f47-a8a0-007e5970c54a.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/71167049/222925713-31c187dd-adec-4666-a6ba-a36f78d39cdd.png">
Also for the frequency range of aquarewave, it is from 100mHz to 10MHz, not to 20MHz. Maybe the notes can be changed later.

**Comment by danchitnis** [comment]
I updated the function in `v0.5.2`, in which there was a bug with the offset voltage, which I now removed. I don't see a problem with the period and timing. I corrected the docs to 100ns to 10s. You have to use scientific notation like:

```python
osc.setWGenPulse(inst, 0, 3.3, 100e-9, 20e-9)
```

**Comment by Wang-Yining-Nicola** [comment]
Got it. I'll try the new functions next week. And the docs for setWGenSquare() need to be changed as well as I mentioned here. The frequency range also need to be changed from 20MHz to 10MHz. Before that I input the wrong range of period on the function for pulse, thus changing them didn't affect the waveform, and that's how I find the issues of the docs. Others who refered to the same docs may face the same problem as me. Will try the new functions later and see if I missed something else.

> <img alt="image" width="515" src="https://user-images.githubusercontent.com/71167049/222925691-e410d769-f84d-4f47-a8a0-007e5970c54a.png">
> 
> <img alt="image" width="922" src="https://user-images.githubusercontent.com/71167049/222925713-31c187dd-adec-4666-a6ba-a36f78d39cdd.png">
> 
> Also for the frequency range of aquarewave, it is from 100mHz to 10MHz, not to 20MHz. Maybe the notes can be changed later.

**Comment by danchitnis** [comment]
corrected on `v0.5.3`. Check it next week to see if it is okay
