### ISSUE TITLE
osc.setWGenRamp

### ISSUE THREAD

**Issue by Wang-Yining-Nicola** [danchitnis/pyscpi#2]
**Describe the bug**
osc.setWGenRamp(osci, 0, 1, 0, 100, 99)
The last parameter (to changing symmetry) should be **int** not float. When I input number from 0.01 to 0.99, nothing changes but when I input number 1 to 99, the waveform changes as expected. So I think should change the document and parameter type.

**Expected behaviour**

**Screenshots**
![1677594528783](https://user-images.githubusercontent.com/71167049/221883592-30ff4585-8273-4929-ba73-2fb990e3b3eb.jpg)
![1677594541991](https://user-images.githubusercontent.com/71167049/221883638-96e2a4cd-c09a-4aae-b4a9-71d54bb3a187.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - pyscpi version: 0.5.0
 - Connection method: Socket

**Comment by danchitnis** [comment]
Fixed in `v0.5.2`
